worker_processes 3; 
events { worker_connections 1024; } 
http { 
    server { 
        listen 80; 
        charset utf-8; 
        location / { 
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ =404;

            location ~* \.css$ {
                default_type text/css;
            }
            location ~* \.js$ {
                default_type application/javascript;
            }
        }
        
        location /user { 
            rewrite ^/user/(.*) /$1 break;
            proxy_pass http://user:8001;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade; 
            proxy_set_header Connection 'upgrade'; 
            proxy_set_header Host $host; 
            proxy_cache_bypass $http_upgrade; 
        }
        location /devices { 
            rewrite ^/devices/(.*) /$1 break;
            proxy_pass http://devices:8002;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade; 
            proxy_set_header Connection 'upgrade'; 
            proxy_set_header Host $host; 
            proxy_cache_bypass $http_upgrade; 
        }
        location /schedules { 
            rewrite ^/schedules/(.*) /$1 break;
            proxy_pass http://schedules:8006;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade; 
            proxy_set_header Connection 'upgrade'; 
            proxy_set_header Host $host; 
            proxy_cache_bypass $http_upgrade; 
        }
        location /widget { 
            rewrite ^/widget/(.*) /$1 break;
            proxy_pass http://widget:8007;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade; 
            proxy_set_header Connection 'upgrade'; 
            proxy_set_header Host $host; 
            proxy_cache_bypass $http_upgrade; 
        }
        location /uploads/ {
            root /usr/share/nginx/html/;
            autoindex on;          # Enables directory listing
            autoindex_exact_size off;  # Show file sizes in a human-readable format
            autoindex_localtime on;    # Display local time for files instead of UTC
        }
    } 
}